### ISSUE TITLE
Application Crash

### ISSUE THREAD

**Issue by Tony-Klink** [katalash/DSMapStudio#9]
I'm trying to create new project for DS1
Steps:
 - Select 'File' -> 'New Project'
 - Set project name and project folder
 - Set game to Dark Souls PTDE
 - Click 'Create'
 Result:
 Error message: "Could not find DS1 regulation file. Functionality will be limited."
Then application closes itself without any logs.

**Comment by katalash** [comment]
You likely haven't run Unpack Dark Souls for Modding (UDSFM), which is needed to run map studio. I apologize for not making the prerequisites more clear.

**Comment by Tony-Klink** [comment]
Running UDSFM resolved the issue.
Thank you for your support!
